FROM node:latest

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

ADD ./package.json /usr/src/app/package.json

RUN npm install

ADD . /usr/src/app

ADD start-server.sh /usr/src/app/start-server.sh
RUN chmod +x /usr/src/app/start-server.sh

EXPOSE 9000

CMD "/usr/src/app/start-server.sh"
