FROM node:latest

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ADD ./package.json /usr/src/app/package.json
RUN npm install

ADD . /usr/src/app

ADD start-client.sh /usr/src/app/start-client.sh
RUN chmod +x /usr/src/app/start-client.sh

EXPOSE 3000

CMD "/usr/src/app/start-client.sh"
